<ol class="breadcrumb">
    <li>
        <i class="fa fa-home">
        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a></i>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>

    <li class="active">
        <i class="fa fa-fw fa-file"></i> Requerimientos
    </li>

     <li class="active">
        <i class="fa fa-file"></i>

        <?php  if (isset($_view_params['menu4'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu4']); $i++):?>         
        <a href="<?php  echo $_view_params['menu4'][$i]['link'];?>"><?php  echo $_view_params['menu4'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>      

    <li class="active">
        <i class="fa fa-file-text"></i> Levantar Requerimiento
    </li>
</ol>

<body>
     <header class="header">
		<div class= "row ">
		    <div class="col-md-12" >
			<form id="valreque" class="form-horizontal" action="<?php  echo BASE_URL;?>requerimientos/nuevorequerimientos" method="post">

		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-user">Datos del Solicitante</h3>
		 			</div>
							
		 			<div class="panel-body">


					<div class="form-group">

						<div class="col-sm-2" class="" id="cedula2">
	   						 <strong><p id="cedula1"></p></strong>
	   					</div>

							<label class="control-label col-sm-1">Cedula</label>
								<div class="col-sm-2">								
									<input type="text" class="form-control" name="cedula" placeholder="Cedula" id="cedula" title="Cedula">										
								</div>

							<label class="control-label col-sm-3">Credencial</label>
								<div class="col-sm-2">								
									<input type="text" class="form-control" name="credencial" placeholder="Credencial" id="credencial" title="credencial">									
								</div>

						<div class="col-sm-2" class="" id="credencial2">
						 		<strong><p id="credencial1"></p></strong>
						</div>										
					</div>							

					<div class="form-group">
						<label class="control-label col-sm-3">Primer Nombre</label>
							<div class="col-sm-3">						
								<input type="text" class="form-control"  name="nombre_1" " placeholder="Primer Nombre" title="nombre_1" >								
							</div>
						<label class="control-label col-sm-2">Segundo Nombre</label>
							<div class="col-sm-3">							
								<input type="text" class="form-control"  name="nombre_2"  placeholder=" Segundo Nombre" title="nombre_2" >								
							</div>
						</div>

					<div class="form-group">
						<label class="control-label col-sm-3">Primer Apellido</label>
							<div class="col-sm-3">
								<input type="text" class="form-control"  name="apellido_1" placeholder="Primer apellido" title="apellido_1" >							
							</div>
						<label class="control-label col-sm-2">Segundo Apellido</label>							
							<div class="col-sm-3">						
								<input type="text" class="form-control"  name="apellido_2"  placeholder=" Segundo apellido" title="apellido_2" >								
							</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-3">Cargo</label>
							<div class="col-sm-3">
								<input type="text" class="form-control"  name="cargo"  placeholder="Cargo" title="Cargo" >
							</div>

						<label class="control-label col-sm-2">Jerarquia</label>
							<div class="col-sm-3">
								<select class="form-control"  name="jerarquia"  id="jerarquia" title="jerarquia" >
									<option>Seleccione...</option>									
								</select>
							</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-5">correo electronico</label>
							<div class="col-sm-3">
									<input type="text"  class="form-control" name="correo"  placeholder="Ingrese un correo" title="Correo">
							</div>
					</div>




		 			</div>
		 		</div>

				<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-user">Despacho</h3>
		 			</div>		 					
		 			<div class="panel-body">

					<div class="form-group">
						<label class="control-label col-sm-4">Numero de contacto</label>
							<div class="col-sm-2">
								<select class="form-control"  name="cod_area" id="cod_area">
									<option>Seleccione...</option>									
								</select>
							</div>
							<div class="col-sm-4">	
									<input type="text" class="form-control" name="num_cel" placeholder="Ingrese un numero de telefono" title="numero de telefono">		
							</div>
					</div>			 			

					<div class="form-group">
						<label class="control-label col-sm-4">Direccion</label>
          
					</div>	

					<div class="form-group">

							<div class="col-sm-4">
								<select class="form-control"  name="areaa" id="areaa">
									<option>Seleccione...</option>
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areab" id="areab">
									<option>Seleccione...</option>										
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areac" id="areac">
									<option>Seleccione...</option>									
								</select>								
							</div>		          
					</div>							
			

		 			</div>
		 		</div>	    

		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading">
		 				<h3 class= "panel-title"> Datos del Requerimiento</h3>
		 			</div>
		 					
		 			<div class="panel-body">		 				

						    <div class="form-group ">
						        <label class="control-label col-sm-3">Fecha del Requerimiento</label>
						            <div class='col-sm-3'>
						            	<div class="input-group">
								        	<input type="text" id="datepicker" name="fecha"  class="form-control">
									 	 <span class="input-group-addon glyphicon glyphicon-calendar"></span>
										</div>									        
								   	</div>

							  	<label class="control-label col-sm-2">Hora </label>
							  		<div class="col-sm-3">
						            	<div class="input-group">							  		
							    			<input id="timepicker1" type="text" class="form-control" name="hora" title="hora">
									 	 <span class="input-group-addon glyphicon glyphicon-time"></span>
										</div>									    									    			
							 		 </div>
						    </div>

							<div class="form-group">
								<label class="control-label col-sm-3">Tipo de Solicitud</label>
									<div class="col-sm-3">
										<select class="form-control" name="tipo_de_solicitud" id="tipo_de_solicitud">
											<option>Seleccione...</option>	
										</select>
									</div>
								<label class="control-label col-sm-2">N°</label>
									<div class="col-sm-3">								
											<input type="text" class="form-control" name="numero" placeholder="N° del documento" id="numero" title="N° del documento">							
									</div>
							</div>

							<div class="form-group">
						        <label class="control-label col-sm-3" >Fecha de la Tramitacion del documento</label>
						            <div class='col-sm-3'>
						            	<div class="input-group">
								        	<input type="text" id="date" name="fecha_documento"  class="form-control">
									 	 <span class="input-group-addon glyphicon glyphicon-calendar"></span>
										</div>									        	
								   	</div>

								<label class="control-label col-sm-2 fa fa">Tipo de Requerimiento</label>
									<div class="col-sm-3">
										<select class="form-control" name="tipo_de_requerimiento" id="tipo_de_requerimiento">
											<option>Seleccione...</option>											
										</select>
									</div>
							</div>

							<div class="form-group">
								<label class="control-label col-sm-3">Sistema</label>
									<div class="col-sm-3">
										<select class="form-control" name="Sistema" id="Sistema">
										<option>Seleccione...</option>
										</select>
									</div>
								<label class="control-label col-sm-2">Modulo</label>
									<div class="col-sm-3">
										<select class="form-control" name="Modulo" id="Modulo">
										<option>Seleccione...</option>
										</select>
									</div>									
							</div>	

							<div class="form-group">
								<label class="control-label col-sm-4">Status</label>
									<div class="col-sm-4">
										<select class="form-control" name="status" id="status">
											<option>Seleccione...</option>										
										</select>
									</div>
							</div>							

							<div class="form-group">
								<label class="control-label col-sm-4">Descripción</label>
									<div class="col-sm-5">

										<textarea type="text" class="form-control" name="descripcion" placeholder="Max 120 Caracteres." maxlength="120" id="descripcion" class=estilotextarea1 cols="60" rows="2"></textarea> 
				
									</div>
							</div>

							<div class="form-group">
								<label class="control-label col-sm-4">Solución</label>
									<div class="col-sm-5">
											<textarea type="text" class="form-control" name="solucion" placeholder="Max 120 Caracteres." maxlength="120" id="solucion" class=estilotextarea2 cols="60" rows="2"></textarea> 					
									</div>

							</div>

							<div class="form-group">
								<label class="control-label col-sm-4">Observación</label>
									<div class="col-sm-5">
											<textarea type="text" class="form-control" name="observaciones" placeholder="Max 120 Caracteres." maxlength="120" id="observaciones" class=estilotextarea2 cols="60" rows="2" ></textarea>					
									</div>

							</div>

						<div class="col-sm-offset-6">
							<input type="submit" value="Registrar" class="btn btn-primary" onclick="return confirm('¿Esta seguro que desea registrar este requerimiento?');">
						</div>
		 		 		
		 			</div>
		 		</div>
		 		
		 	
		 		</form>	
		 	</div>
		</div>
	</header>
</body>
</html>