<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-user"></i> Mis datos Personales
    </li>
</ol>


     <div id="page-wrapper">
		<div class="container">
			<div class="col-md-12 col-md-offset-0" >
    	 			<div class="panel-body">
    					<div class="dataTable_wrapper">
    	 					<form id="personuser" action="<?php  echo BASE_URL;?>persons/consultauser" method="post">
    	 						<table class="table table-striped table-bordered table-hover" >
                                        <thead>
                                            <tr>                                        	
                                                <th>Cedula</th>
                                                <th>Nombre y Apellido</th>                    
                                                <th>Nombre de usuario</th>
                                                <th>Pregunta</th>                                          
                                                <th>Respuesta</th>                                        
                                                <th>Perfil</th>                                          
                                                <th>Editar</th>                          

                                            </tr>
                                        </thead>                                 
                                        <tbody>
                                <?php foreach ($this->_lista as $usuario): ?>
                                    <tr class="info">                                   
                                        <td align="center"><?php echo $usuario['cedula'];?></td>
                                        <td align="center">

                                        <?php echo $usuario['nombre_1'];?>
                                        <?php echo $usuario['apellido_1'];?>
                                            
                                        </td>
                                        <td align="center"><?php echo $usuario['usuario'];?></td>                                                                
                                        <td align="center"><?php echo $usuario['pregunta'];?></td>
                                        <td align="center"><?php echo $usuario['respuesta'];?></td>
                                        <td align="ceneter"><?php echo $usuario['perfil'];?></td>
                                       
                                        <td align="center">                                    	
               								<a href="<?php echo BASE_URL."persons/updatedatospersonales/". $usuario['id'] ; ?>">
                                                <span title="Cambiar datos" class="glyphicon glyphicon-edit"></span>                                         
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                                        </tbody>
                                    </table>
    	 		 			</form>


    	 				</div>
    	 			</div>            
	 		</div>
	 	</div>
	</div>	 	

            <br><br>
        <br><br>
    <br><br>
<br><br><br>
