<ol class="breadcrumb">
    <li>
        <i class="fa fa-home"></i>

        <?php  if (isset($_view_params['menu'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu']); $i++):?>         
        <a href="<?php  echo $_view_params['menu'][$i]['link'];?>"><?php  echo $_view_params['menu'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>
    <li class="active">
        <i class="fa fa-user"></i> Gestion de Usuarios
    </li>

    <li>
        <i class="fa fa-user"></i>

        <?php  if (isset($_view_params['menu2'])):?>
        <?php  for ($i= 0; $i < count($_view_params['menu2']); $i++):?>         
        <a href="<?php  echo $_view_params['menu2'][$i]['link'];?>"><?php  echo $_view_params['menu2'][$i]['title']; ?></a>

        <?php  endfor;?>
        <?php  endif;?> 

    </li>    

    <li class="active">
        <i class="fa fa-edit"></i> Nuevo Registro
    </li>
</ol>

<body>
     <header class="header">
		<div class="row">
		    <div class="col-md-12" >
		    	<form  id="personuser" class="form-horizontal" action="<?php  echo BASE_URL;?>persons/insert"	method="post">

		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-user">Datos Basicos</h3>
		 			</div>
		 					
		 			<div class="panel-body">



							<div class="form-group">

        					<div class="col-sm-2" class="" id="cedula2">
           						 <strong><p id="cedula1"></p></strong>
           					</div>

								<label class="control-label col-sm-1">Cedula</label>
									<div class="col-sm-2">								
										<input type="text" class="form-control" name="cedula" placeholder="Cedula" id="cedula" title="Cedula">										
									</div>
	
								<label class="control-label col-sm-3">Credencial</label>
									<div class="col-sm-2">								
										<input type="text" class="form-control" name="credencial" placeholder="Credencial" id="credencial" title="credencial">									
									</div>
									<div class="col-sm-2" class="" id="credencial2">
           						 		<strong><p id="credencial1"></p></strong>
           							</div>										
							</div>	



					<div class="form-group">
						<label class="control-label col-sm-3">Primer Nombre</label>
							<div class="col-sm-3">						
								<input type="text" class="form-control" name="nombre_1" placeholder="Primer Nombre" title="nombre_1">								
							</div>
						<label class="control-label col-sm-2">Segundo Nombre</label>
							<div class="col-sm-3">							
								<input type="text" class="form-control" name="nombre_2" placeholder=" Segundo Nombre" title="nombre_2">									
							</div>
						</div>

					<div class="form-group">
						<label class="control-label col-sm-3">Primer Apellido</label>
							<div class="col-sm-3">
								<input type="text" class="form-control" name="apellido_1" placeholder="Primer apellido" title="apellido_1">							
							</div>
						<label class="control-label col-sm-2">Segundo Apellido</label>							
							<div class="col-sm-3">						
								<input type="text" class="form-control" name="apellido_2" placeholder=" Segundo apellido" title="apellido_2">
							
							</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-3">Cargo</label>
							<div class="col-sm-3">

								<input type="text" class="form-control" name="cargo" placeholder="cargo" title="cargo">

							</div>

						<label class="control-label col-sm-2">Jerarquia</label>
							<div class="col-sm-3">
								<select class="form-control"  name="jerarquia" id="jerarquia">
									<option>Seleccione...</option>									
								</select>
							</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-5">correo electronico</label>
							<div class="col-sm-3">

									<input type="text" class="form-control" name="correo" placeholder="Ingrese un correo" title="correo">

							</div>
					</div>
		 		</div>
		 		</div>

				<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-user">Despacho</h3>
		 			</div>		 					
		 			<div class="panel-body">


					<div class="form-group">

							<div class="col-sm-4">
								<select class="form-control"  name="areaa" id="areaa">
									<option>Seleccione...</option>
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areab" id="areab">
									<option>Seleccione...</option>										
								</select>								
							</div>

							<div class="col-sm-4">
								<select class="form-control"  name="areac" id="areac">
									<option>Seleccione...</option>									
								</select>								
							</div>			          
					</div>					
			

		 			</div>
		 		</div>	    

		 		<div class= "panel panel-primary" >
		 			<div class= "panel-heading" >
		 				<h3 class= "panel-title fa fa-users">Usuario</h3>
		 			</div>
		 					
		 			<div class="panel-body">


					<div class="form-group">
						<label class="control-label col-sm-5">usuario</label>
							<div class="col-sm-3">
									<input type="text" class="form-control" name="usuario" placeholder="Ingrese aca su usuario" id="usuario" title="usuario">
							</div>
							    <div class="col-sm-2" class="" id="usuario2">
							         <strong><p id="usuario1"></p></strong>
					        	</div>
					</div>

					<div class="form-group">
						<label class="control-label col-sm-5 ">Clave</label>
							<div class="col-sm-3">
									<input type="password" class="form-control" name="clave" placeholder="ingrese una clave" title="clave" id="clave" required="8">	
							</div>
					              <div class="col-sm-4">
					                <strong><p id="texto"></p></strong>
					              </div>							
					</div>

					<div class="form-group">
						<label class="control-label col-sm-5 ">Repita su Clave</label>
							<div class="col-sm-3">
									<input type="password" class="form-control" name="clave1" placeholder="ingrese una clave" title="clave1" id="clave1" required="8">	
							</div>
					              <div class="col-sm-4">
					                <strong><p id="val"></p></strong>
					              </div>							
					</div>

					<div class="form-group">
              			<label class="control-label col-sm-5">pregunta </label>
              				<div class="col-sm-3">
                				<input type="text"  class="form-control" name="pregunta" placeholder="Ingrese su pregunta" title="pregunta" id="pregunta" >
              				</div>
            		</div>

					<div class="form-group">
              			<label class="control-label col-sm-5">respuesta </label>
              				<div class="col-sm-3">
                				<input type="text" class="form-control" name="respuesta" placeholder="Ingrese su respuesta" title="respuesta" id="respuesta" >
              				</div>
            		</div>					

					<div class="form-group">
						<label class="control-label col-sm-5">Perfil</label>
							<div class="col-sm-3">
								<select  class="form-control " name="perfil" id="perfil" class="">

									<option>Seleccione...</option>
								</select>
							</div>
					</div>


					<div class="col-sm-offset-6">
						<input type="submit" value="Registrar" class="btn btn-primary" onclick=" return confirm('¿Estas seguro de realizar este registro?');">
					</div>
							

		 			</div>
		 		</div>		 		
			 </form>
		</div>
		</div>
	</header>
</body>	

<select class="js-example-basic-multiple" name="states[]" multiple="multiple">
  <option value="AL">Alabama</option>
    ...
  <option value="WY">Wyoming</option>
</select>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>