<br>
<div id="page-wrapper">
  <div class= "container ">
    <div  class= "col-md-8 col-md-offset-2">
      <div class= "panel panel-info">
          <div class= "panel-heading" align="center">
            <h3 class= "panel-title"> Recuperacion</h3>
          </div>

          <div class="panel-body">
              <h3 align="center"><?php echo $this->mensaje ?></h3>
              <label><a href="<?php echo $_view_params['login']['href'];?>">INICIAR SESION</label>
          </div>

          <br>

      </div>
    </div>
  </div>
</div>

<br><br><br>
<br><br><br>
<br><br><br>