
<div id="page-wrapper">
	<div class= "container ">
		<div class="col-md-12 " >
			<form  class="form-horizontal" action="<?php  echo BASE_URL;?>recuperar/recuperar_c" method="post">	
				<div class= "panel panel-info" >
					<div class= "panel-heading">
						<h3 class= "panel-title fa fa-users"> Recuperacion de clave de Usuario</h3>
					</div>
						<div class="panel-body">
							<?php if (isset($this->_error)) echo $this->_error; ?>
							<div class="form-group">
							<label class="control-label col-sm-4 glyphicon glyphicon-user">usuario</label>
							<div class="col-sm-4">
								<input type="text" class="form-control" name="usuario"  placeholder="Ingrese aca su usuario" id="usuario" title="usuario" style="text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase()">
							</div>
							<div class="col-sm-4" class="" id="usuario2">
								<strong><p id="usuario1"></p></strong>
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-sm-4 fa fa-pencil-square-o">pregunta </label>
							<div class="col-sm-4">
								<input type="text" class="form-control" name="pregunta" placeholder="Ingrese su pregunta" title="pregunta" id="pregunta" >
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-sm-4 fa fa-pencil-square-o">respuesta </label>
							<div class="col-sm-4">
								<input type="text" class="form-control" name="respuesta" placeholder="Ingrese su respuesta" title="respuesta" id="respuesta" >
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-sm-4 fa fa-key">Nueva Clave</label>
							<div class="col-sm-4">
								<input type="password" class="form-control" name="clave" placeholder="ingrese una clave" title="clave" id="clave" required="8">	
							</div>
							<div class="col-sm-4">
								<strong><p id="texto"></p></strong>
							</div>
						</div>

						<div class="form-group">
							<label class="control-label col-sm-4 fa fa-key">Repita su Clave</label>
							<div class="col-sm-4">
								<input type="password" class="form-control" name="clave1" placeholder="ingrese una clave" title="clave1" id="clave1" required="8">
							</div>
							<div class="col-sm-4">
								<strong><p id="val"></p></strong>
							</div>
						</div>

						<div class="col-sm-offset-5">
							<input type="submit" value="Enviar datos" class="btn btn-primary">
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<br><br>
<br><br>


