<body>
    <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="block"> 
                        <div class="footer-contant">                  
                            <ul class="list-inline text-center">
                                <h4>"Policía Científica Servidores de la Patria para la Paz y la vida"</h4>
                                <p>Desarrollado por:</p>
                                <p>Dirección de Tecnología-División de Sístemas</p>
                                <p>Cuerpo de Investigaciones Cientifica Penales y Criminalisticas ( CICPC ).
                                <br> Todos los Derechos Reservados</p>
                            </ul>
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </section>
    
        <script src="<?php echo PUBLIC_URL; ?>js/jquery.min.js"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/jquery.dataTables.min.js"></script> 
        <script src="<?php echo PUBLIC_URL; ?>js/dataTables.bootstrap.min.js"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
        <script src="<?php echo PUBLIC_URL; ?>js/bootstrap.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/bootstrapValidator.min.js"></script>   
        <script src="<?php echo PUBLIC_URL;?>js/ajax/main.js"></script>
        <script src="<?php echo PUBLIC_URL;?>js/jquery-ui.js"></script>


           <!-- / START - page related files and scripts [optional] -->
    <?php  if (isset($_view_params['js']) && count($_view_params['js'])): ?>
    <?php   for ($i = 0; $i < count($_view_params['js']); $i++):  ?>
        <script src="<?php echo $_view_params['js'][$i]; ?>"></script>
    <?php   endfor; ?>
    <?php  endif;?>
    <!-- / END - page related files and scripts [optional] -->
    </footer><!--/#footer-->
</body>
</html>

  